apiVersion: v1
kind: ConfigMap
metadata:
  name: equities-config
  namespace: equities
data:
  DJANGO_DEBUG: "0"
  DJANGO_SETTINGS_MODULE: "project.settings"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis:6379/0"
  CORS_ALLOWED_ORIGINS: "http://localhost"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "false"
  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
