# Generated by Django 4.2.23 on 2025-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
