# Generated by Django 4.2.23 on 2025-08-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('TSX', 'TSX'), ('TSXV', 'TSX Venture Exchange')], db_index=True, max_length=8)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('listing_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['exchange', 'symbol'],
                'unique_together': {('exchange', 'symbol')},
            },
        ),
    ]
