# Generated by automated patch: add status and active to Listing
from django.db import migrations, models


def set_active_from_status(apps, schema_editor):
    Listing = apps.get_model('stocks', 'Listing')
    for obj in Listing.objects.all():
        if obj.status in ('delisted', 'suspended'):
            obj.active = False
        else:
            obj.active = True
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('listed', 'Currently Listed'), ('recent', 'Recently Listed'), ('delisted', 'Recently Delisted'), ('suspended', 'Suspended')], default='listed', max_length=16, db_index=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True, db_index=True),
        ),
        migrations.RunPython(set_active_from_status, lambda apps, schema: None),
    ]
