# Generated by Django 4.2.23 on 2025-08-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_etfinfo_geographicregion_sector_alter_listing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicregion',
            name='region_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='geographicregion',
            unique_together={('region_name', 'country_name')},
        ),
    ]
