# Generated by Django 4.2.23 on 2025-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_geographicregion_region_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Individual Stock'), ('ETF', 'Exchange Traded Fund'), ('MUTUAL_FUND', 'Mutual Fund'), ('REIT', 'Real Estate Investment Trust'), ('TRUST', 'Business/Income Trust'), ('BOND', 'Bond/Fixed Income'), ('WARRANT', 'Warrant'), ('RIGHTS', 'Rights'), ('PREFERRED', 'Preferred Share'), ('UNIT', 'Unit/Hybrid Security'), ('CRYPTO', 'Cryptocurrency Product'), ('COMMODITY', 'Commodity Fund'), ('OTHER', 'Other/Unknown')], db_index=True, default='STOCK', help_text='Type of financial instrument', max_length=20),
        ),
    ]
