# Generated by Django 4.2.23 on 2025-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_listing_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='YFinanceSectorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_key', models.CharField(db_index=True, help_text="yfinance sector key (e.g., 'technology')", max_length=50, unique=True)),
                ('sector_name', models.CharField(help_text='Human-readable sector name', max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('overview', models.TextField(blank=True, help_text='Sector overview/description', null=True)),
                ('has_top_etfs', models.BooleanField(default=False)),
                ('has_top_companies', models.BooleanField(default=False)),
                ('has_top_mutual_funds', models.BooleanField(default=False)),
                ('has_industries', models.BooleanField(default=False)),
                ('has_research_reports', models.BooleanField(default=False)),
                ('top_etfs_data', models.JSONField(blank=True, help_text='Cached top ETFs data', null=True)),
                ('top_companies_data', models.JSONField(blank=True, help_text='Cached top companies data', null=True)),
                ('top_mutual_funds_data', models.JSONField(blank=True, help_text='Cached mutual funds data', null=True)),
                ('industries_data', models.JSONField(blank=True, help_text='Cached industries data', null=True)),
                ('research_reports_data', models.JSONField(blank=True, help_text='Cached research reports', null=True)),
                ('data_fetched_at', models.DateTimeField(auto_now_add=True, help_text='When data was fetched from yfinance')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('fetch_error', models.TextField(blank=True, help_text='Last fetch error if any', null=True)),
                ('fetch_success', models.BooleanField(default=True, help_text='Whether last fetch was successful')),
            ],
            options={
                'verbose_name': 'YFinance Sector Cache',
                'verbose_name_plural': 'YFinance Sector Cache',
                'db_table': 'yfinance_sector_cache',
                'ordering': ['sector_name'],
            },
        ),
        migrations.CreateModel(
            name='YFinanceStockSectorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32, unique=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('sector_key', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_key', models.CharField(blank=True, max_length=50, null=True)),
                ('data_fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fetch_success', models.BooleanField(default=True)),
                ('fetch_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Sector Cache',
                'verbose_name_plural': 'Stock Sector Cache',
                'db_table': 'yfinance_stock_sector_cache',
                'ordering': ['symbol'],
            },
        ),
    ]
