# Generated by Django 4.2.23 on 2025-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_add_yfinance_caching_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Stock symbol (e.g., AAPL, SHOP.TO)', max_length=32)),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange', max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name', max_length=200, null=True)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Individual Stock'), ('ETF', 'Exchange Traded Fund'), ('MUTUAL_FUND', 'Mutual Fund'), ('REIT', 'Real Estate Investment Trust'), ('TRUST', 'Business/Income Trust'), ('BOND', 'Bond/Fixed Income'), ('WARRANT', 'Warrant'), ('RIGHTS', 'Rights'), ('PREFERRED', 'Preferred Share'), ('UNIT', 'Unit/Hybrid Security'), ('CRYPTO', 'Cryptocurrency Product'), ('COMMODITY', 'Commodity Fund'), ('OTHER', 'Other/Unknown')], db_index=True, default='OTHER', max_length=20)),
                ('asset_confidence', models.FloatField(default=0.0, help_text='Confidence score for asset classification (0-1)')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('sector_key', models.CharField(blank=True, help_text='yfinance sector key for detailed analysis', max_length=50, null=True)),
                ('industry_key', models.CharField(blank=True, help_text='yfinance industry key', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO country code', max_length=8, null=True)),
                ('region', models.CharField(blank=True, db_index=True, help_text='Geographic region (North America, Europe, etc.)', max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization in USD', null=True)),
                ('currency', models.CharField(blank=True, help_text='Trading currency', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the ticker is actively trading')),
                ('data_source', models.CharField(default='yfinance', help_text='Primary data source used', max_length=50)),
                ('data_quality_score', models.FloatField(default=0.0, help_text='Overall data completeness score (0-1)')),
                ('fetch_success', models.BooleanField(default=True, help_text='Whether data fetch was successful')),
                ('fetch_errors', models.JSONField(blank=True, help_text='Any errors encountered during fetch', null=True)),
                ('first_loaded_at', models.DateTimeField(auto_now_add=True, help_text='When this ticker was first processed')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('last_checked_at', models.DateTimeField(auto_now=True, help_text='When this ticker was last checked by DAG')),
                ('data_changed_at', models.DateTimeField(blank=True, help_text='When the ticker data last actually changed', null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, help_text='Hash of key data fields for change detection', max_length=64, null=True)),
                ('version', models.IntegerField(default=1, help_text='Version number, incremented on changes')),
            ],
            options={
                'verbose_name': 'Enriched Ticker Data',
                'verbose_name_plural': 'Enriched Ticker Data',
                'db_table': 'enriched_ticker_data',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol', '-version'], name='enriched_ti_symbol_24d1e5_idx'), models.Index(fields=['asset_type', 'sector'], name='enriched_ti_asset_t_3ebf51_idx'), models.Index(fields=['country', 'region'], name='enriched_ti_country_1c314d_idx'), models.Index(fields=['last_checked_at'], name='enriched_ti_last_ch_9834d8_idx'), models.Index(fields=['data_hash'], name='enriched_ti_data_ha_e7034d_idx')],
                'unique_together': {('symbol', 'version')},
            },
        ),
    ]
