# Generated by Django 4.2.29 on 2026-04-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_add_enriched_ticker_data_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('TFSA', 'Tax-Free Savings Account'), ('FHSA', 'First Home Savings Account')], max_length=20)),
                ('institution', models.CharField(default='Wealthsimple', max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIV', 'Dividend (Cash)'), ('DRIP', 'Dividend Reinvested'), ('CONT', 'Contribution'), ('WDR', 'Withdrawal'), ('LOAN', 'Share Loan'), ('RECALL', 'Loan Recall'), ('INTEREST', 'Interest')], max_length=10)),
                ('date', models.DateField()),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('is_drip', models.BooleanField(default=False)),
                ('statement_period', models.CharField(blank=True, max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stocks.portfolio')),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'indexes': [models.Index(fields=['portfolio', 'symbol', 'date'], name='stocks_tran_portfol_caca3d_idx'), models.Index(fields=['portfolio', 'date'], name='stocks_tran_portfol_8ea41b_idx')],
            },
        ),
    ]
