# Generated by Django 4.2.29 on 2026-04-05 05:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('segregated_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('statement_period', models.CharField(blank=True, max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stocks.portfolio')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('portfolio', 'symbol', 'statement_period')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioCashSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_statement_cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_cash_paid_in', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_cash_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('closing_cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('contributions_ytd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('statement_period', models.CharField(blank=True, max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_summaries', to='stocks.portfolio')),
            ],
            options={
                'ordering': ['-statement_period'],
                'unique_together': {('portfolio', 'statement_period')},
            },
        ),
    ]
