# Generated by Django 4.2.29 on 2026-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_portfolio_account_number_portfolioholding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('interval', models.CharField(default='15m', max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='stocks_intr_symbol_841039_idx'), models.Index(fields=['symbol', 'interval'], name='stocks_intr_symbol_3e0558_idx')],
                'unique_together': {('symbol', 'timestamp', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('adj_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='stocks_hist_symbol_bfe1be_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
