# Generated by Django 4.2.29 on 2026-05-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_intradayprice_historicalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VettaFiIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('equity_benchmark', 'Equity Benchmark'), ('fixed_income_benchmark', 'Fixed Income Benchmark'), ('factor', 'Factor'), ('thematic', 'Thematic'), ('custom_equity', 'Custom Equity'), ('assets', 'Assets'), ('derivatives', 'Derivatives'), ('strategy', 'Strategy')], db_index=True, max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, choices=[('north_america', 'North America'), ('emea', 'EMEA'), ('asia_pacific', 'Asia-Pacific'), ('latin_america', 'Latin America'), ('global', 'Global'), ('japan', 'Japan'), ('global_ex_us', 'Global (ex-US)'), ('developed', 'Developed'), ('developed_ex_us', 'Developed (ex-US)'), ('emerging_markets', 'Emerging Markets'), ('americas', 'Americas'), ('other', 'Other')], max_length=50, null=True)),
                ('factsheet_url', models.URLField(blank=True, null=True)),
                ('methodology_url', models.URLField(blank=True, null=True)),
                ('index_page_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vettafi_index',
                'ordering': ['ticker'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'transaction_type'], name='stocks_tran_portfol_c0d0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='vettafiindex',
            index=models.Index(fields=['category', 'region'], name='vettafi_ind_categor_f5efa7_idx'),
        ),
        migrations.AddIndex(
            model_name='vettafiindex',
            index=models.Index(fields=['category', 'sub_category'], name='vettafi_ind_categor_669f93_idx'),
        ),
    ]
